### ISSUE TITLE
There is a problem with plug-in use.

### ISSUE THREAD

**Issue by 879492767** [kayc01/PixelmonGym_Sponge#3]
[19:19:15] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'pixelgym addleader rock _callme' for source EntityPlayerMP['_callme'/64, l='world', x=43.70, y=122.35, z=-310.36]: 0
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60) ~[minecraft_server.1.12.2.jar:?]
        at me.Ckay.gym.commands.PixelGymAdminCommand.execute(PixelGymAdminCommand.java:167) ~[PixelGymAdminCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2955]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_162]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2955]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedSe

**Comment by 879492767** [comment]
[19:17:34] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=pixelgym, name=PixelmonGym, version=2.5, source=D:服务端测试\1.12.2\mods\PixelGym-2.5.jar}
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60) ~[minecraft_server.1.12.2.jar:?]
        at me.Ckay.gym.scoreboard.ScoreboardManager.init(ScoreboardManager.java:49) ~[ScoreboardManager.class:?]
        at me.Ckay.gym.scoreboard.ScoreboardManager.<init>(ScoreboardManager.java:31) ~[ScoreboardManager.class:?]
        at me.Ckay.gym.PixelGym.onGameStarted(PixelGym.java:379) ~[PixelGym.class:?]
at org.spongepowered.common.event.listener.GameStartedServerEventListener_PixelGym_onGameStarted43.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:240) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-2955]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.
19:18:15] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=pixelgym, name=PixelmonGym, version=2.5, source=D:服务端测试\1.12.2\mods\PixelGym-2.5.jar}
java.lang.NullPointerException: null
        at me.Ckay.gym.scoreboard.ScoreboardManager.removeScores(ScoreboardManager.java:105) ~[ScoreboardManager.class:?]
        at me.Ckay.gym.scoreboard.ScoreboardManager.updateScoreboard(ScoreboardManager.java:136) ~[ScoreboardManager.class:?]
        at me.Ckay.gym.PixelGym.onJoin(PixelGym.java:836) ~[PixelGym.class:?]
        at org.spongepowered.common.event.listener.JoinListener_PixelGym_onJoin46.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:312) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:364) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2955]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2955]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1658) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.

**Comment by 879492767** [comment]
![image](https://user-images.githubusercontent.com/37323543/37565385-718d0cac-2ae3-11e8-9823-be95ce14b4d0.png)
